---
workshop_id: OX3DS20210421_01
topic: open-code
title: "Sharing your paradigms at WIN: a practical introduction"
instructors:
  - Laurence Hunt
  - Dejan Draschkow
instructor_emails:
  - laurence.hunt@psych.ox.ac.uk
  - dejan.draschkow@psych.ox.ac.uk
helpers: []
start_times:
  - 13|00
setup_files:
  - git
language: en
venue: Wellcome Centre for Integrative Neuroimaging, University of Oxford
address: FMRIB Centre, John Radcliffe Hospital, Headington, Oxford OX3 9DU
country: GB
latitude: null
longitude: null
start_date: null
collaborative_notes: null
eventbrite: null
optional_intro_sections:
  - requirements
  - accessibility
kind: workshop
ukrn_email: training@ukrn.org
ukrn_site: https://ukrn.org/
repository: <USERNAME>/<PROJECT>
carpentries_site: https://carpentries.org/
pre_survey: https://docs.google.com/forms/d/e/1FAIpQLScWW7rKXwzUG7PbCkzUH9Vxycg2i8Drk_cJqC_58F1WY1N1bA/viewform?usp=pp_url&entry.2087576176=
post_survey: https://docs.google.com/forms/d/e/1FAIpQLSf1UveYPOWn5zV7DkKO7a5tpNpBqYfEF6rLkDUSurIDe5wwFg/viewform?usp=pp_url&entry.579599320=
collections:
  episodes:
    output: true
    permalink: /:path/index.html
  episodes_rmd:
    output: true
    permalink: /:path/index.html
  extras:
    output: true
    permalink: /:path/index.html
defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page
exclude:
  - Makefile
  - bin/
  - .Rproj.user/
highlighter: rouge
ukrn_wb:
  - fields_structure:
      - name
      - type
      - help
      - is_array
      - is_required
      - format
      - special
  - fields:
      - workshop_id:
          - Workshop identifier
          - string
          - We will provide this to you, but its general structure will be a
            2-3-letter code for your university or institution, a 2-letter code
            for the topic, the date (today's or the intended workshop date) in
            YYYYMMDD format, followed by an underscore and a two-digit version
            number. It should look something like UOBDS20210418_01
          - false
          - true
          - null
          - null
      - topic:
          - Workshop topic
          - string
          - The topic is used to search for pre-existing lessons you can include
            in your workshop
          - false
          - true
          - topic
          - null
      - title:
          - Workshop title
          - string
          - The title should let people know the most important information -
            where the workshop is and what it covers
          - false
          - true
          - null
          - null
      - instructors:
          - Workshop instructor(s)
          - string
          - Instructor name(s)
          - true
          - true
          - null
          - null
      - instructor_emails:
          - Contact email address(es)
          - string
          - Instructor email address(es) for questions/comments/feedback
          - true
          - null
          - email
          - null
      - helpers:
          - Workshop helper(s)
          - string
          - Helper name(s)
          - true
          - null
          - null
          - null
      - start_times:
          - Start time
          - time
          - Start times (in 0900 format) for each day of the workshop. If
            shorter than the number of days, remaining days will use the first
            entry
          - true
          - true
          - hours_minutes
          - null
      - setup_files:
          - Setup instructions
          - filename
          - List of setup guides to include on the homepage
          - true
          - null
          - null
          - - _includes/install_instructions
      - language:
          - Workshop language
          - string
          - Language code for the language the workshop will be conducted in
          - null
          - null
          - iso-639-1
          - null
      - venue:
          - Workshop venue
          - string
          - The brief name of the institution that hosts the workshop without
            address (e.g., "Euphoric State University")
          - null
          - null
          - null
          - null
      - address:
          - Venue address
          - string
          - The full street address of workshop (e.g., "Room A, 123 Forth
            Street, Blimingen, Euphoria"), videoconferencing URL, or 'online'
          - null
          - null
          - long
          - null
      - country:
          - Workshop country
          - string
          - Country code for the institution that hosts the workshop
          - null
          - null
          - iso-3166-1-alpha-2
          - null
      - latitude:
          - Workshop latitude
          - number
          - Latitude of workshop venue (use <a
            href="https://www.latlong.net/">https://www.latlong.net"</a>)
          - null
          - null
          - latitude
          - null
      - longitude:
          - Workshop longitude
          - number
          - Longitude of workshop venue (use <a
            href="https://www.latlong.net/">https://www.latlong.net"</a>)
          - null
          - null
          - longitude
          - null
      - start_date:
          - Workshop start date
          - date
          - Date the workshop starts.
          - null
          - null
          - years-months-days
          - null
      - collaborative_notes:
          - Collaborative notes link
          - string
          - URL for the workshop collaborative notes, e.g. an Etherpad or Google
            Docs document
          - null
          - null
          - null
          - null
      - eventbrite:
          - Eventbrite key
          - string
          - The alphanumeric key for Eventbrite registration, e.g.,
            "1234567890AB"
          - null
          - null
          - null
          - null
      - optional_intro_sections:
          - Optional introductory sections
          - filename
          - Optional introductory sections which can be included on the homepage
            and customised
          - true
          - null
          - null
          - - _includes/intro/optional

---
null